//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EmailRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EmailRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HPCDS.Resources.EmailRes", typeof(EmailRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is an automatically generated email from the High Priority Chemicals Data System (HPCDS).&lt;/p&gt;
        ///&lt;p&gt;Please confirm your HPCDS account by clicking the following link: &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If clicking this link does not work, try copying and pasting the URL into the address bar of your web browser.&lt;/p&gt;
        ///&lt;p&gt;If you need help, please contact the HPCDS application administrator, Topher Buck, at 617-367-8558 x309 or tbuck@newmoa.org&lt;/p&gt;
        ///&lt;p&gt;Please do not respond to this email.&lt;/p&gt;.
        /// </summary>
        public static string EmailValidationBodyFormat {
            get {
                return ResourceManager.GetString("EmailValidationBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your HPCDS account.
        /// </summary>
        public static string EmailValidationSubjectFormat {
            get {
                return ResourceManager.GetString("EmailValidationSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is an automatically generated email from the High Priority Chemicals Data System (HPCDS).&lt;/p&gt;
        ///&lt;p&gt;A new user has created an HPCDS account for an organization with no other users: {0} for {1}. &lt;/p&gt;
        ///&lt;p&gt;To approve this user, please click on the &lt;a href=&quot;{2}?email={0}&amp;code={3}&quot;&gt;Approve New User Link&lt;/a&gt;. Once approved, the new user will receive an email with login instructions and no further action is required on your part.&lt;/p&gt;
        ///&lt;p&gt;If the Approve New User Link above does not work, try copying and pasti [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationApprovalReqForAdminBodyFormat {
            get {
                return ResourceManager.GetString("RegistrationApprovalReqForAdminBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPCDS new user account for new organization.
        /// </summary>
        public static string RegistrationApprovalReqForAdminSubjectFormat {
            get {
                return ResourceManager.GetString("RegistrationApprovalReqForAdminSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is an automatically generated email from the High Priority Chemicals Data System (HPCDS).&lt;/p&gt;
        ///&lt;p&gt;A new user has created an HPCDS account and requested to join your organization: {0}. &lt;/p&gt;
        ///&lt;p&gt;To approve this user, please click on the &lt;a href=&quot;{2}?email={0}&amp;code={3}&quot;&gt;Approve New User Link&lt;/a&gt;. Once approved, the new user will receive an email with login instructions and no further action is required on your part.&lt;/p&gt;
        ///&lt;p&gt;If you believe you received this message in error, simply delete this email. &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string RegistrationApprovalReqForOrgUsersBodyFormat {
            get {
                return ResourceManager.GetString("RegistrationApprovalReqForOrgUsersBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPCDS new user account for your organization.
        /// </summary>
        public static string RegistrationApprovalReqForOrgUsersSubjectFormat {
            get {
                return ResourceManager.GetString("RegistrationApprovalReqForOrgUsersSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is an automatically generated e-mail from the High Priority Chemicals Data System (HPCDS).&lt;/p&gt;
        ///&lt;br/&gt;You have requested an HPCDS account password reset; however, the HPCDS does not contain an account associated with this email address. You may create an account at &lt;a href=&apos;{0}&apos;&gt;https:\\hpcds.theic2.org&lt;/a&gt;.&lt;br/&gt;&lt;br/&gt;
        ///&lt;/p&gt;If you need help, please contact the HPCDS application administrator, Topher Buck, at 617-367-8558 x309 or tbuck@newmoa.org&lt;br/&gt;&lt;br/&gt;
        ///&lt;p&gt;Please do not respond to this email.&lt;/p&gt;.
        /// </summary>
        public static string ResetPWD_NotRegisterdUserBodyFormat {
            get {
                return ResourceManager.GetString("ResetPWD_NotRegisterdUserBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPCDS account reset information.
        /// </summary>
        public static string ResetPWD_NotRegisterdUserSubjectFormat {
            get {
                return ResourceManager.GetString("ResetPWD_NotRegisterdUserSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is an automatically generated email from the High Priority Chemicals Data System (HPCDS).&lt;/p&gt;
        ///&lt;p&gt;Our records show that you have not validated your email address. Please validate your email address by clicking on the following link: &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If clicking the link above does not work, try copying and pasting the URL into the address bar of your web browser.&lt;/p&gt; 
        ///&lt;p&gt;After validating your email address, return to the Login Page: &lt;a href=&apos;{1}&apos;&gt;{1}&lt;/a&gt; and click on &lt;a href=&apos;{2}&apos;&gt;Forg [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResetPWD_NotVerifiedUserBodyFormat {
            get {
                return ResourceManager.GetString("ResetPWD_NotVerifiedUserBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPCDS account reset information.
        /// </summary>
        public static string ResetPWD_NotVerifiedUserSubjectFormat {
            get {
                return ResourceManager.GetString("ResetPWD_NotVerifiedUserSubjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;This is an automatically generated email from the High Priority Chemicals Data System (HPCDS).&lt;/p&gt;
        ///&lt;p&gt;You have requested a password reset for your HPCDS account. Please click the following link and follow the instructions provided to reset your password: &lt;a href=&apos;{0}&apos;&gt;{0}&lt;/a&gt;&lt;/p&gt;
        ///&lt;p&gt;If clicking this link does not work, try copying and pasting the URL into the address bar of your web browser.&lt;/p&gt;
        ///&lt;p&gt;If you need help, please contact the HPCDS application administrator, Topher Buck, at 617-367-8558 x309  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ResetPWD_RegisterdUserBodyFormat {
            get {
                return ResourceManager.GetString("ResetPWD_RegisterdUserBodyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HPCDS account reset information.
        /// </summary>
        public static string ResetPWD_RegisterdUserSubjectFormat {
            get {
                return ResourceManager.GetString("ResetPWD_RegisterdUserSubjectFormat", resourceCulture);
            }
        }
    }
}
