//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryBNPMChemical
    {
        public int InventoryBNPMChemicalId { get; set; }
        public int InventoryBNPMId { get; set; }
        public int ChemicalId { get; set; }
        public string VT_ManufacturerID { get; set; }
        public string VT_ChemicalID { get; set; }
        public string VT_ChemicalNameDescription { get; set; }
        public string VT_BrandName { get; set; }
        public string VT_ProductModel { get; set; }
        public Nullable<int> cntDisclosures { get; set; }
    
        public virtual InventoryBNPM InventoryBNPM { get; set; }
        public virtual Chemical Chemical { get; set; }
    }
}
