//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Report()
        {
            this.ReportAccountableOrganizations = new HashSet<ReportAccountableOrganization>();
            this.ReportDetails = new HashSet<ReportDetail>();
        }
    
        public int ReportId { get; set; }
        public Nullable<int> ProductBrickId { get; set; }
        public int ReporterOrganizationId { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> CopiedFromReportId { get; set; }
        public string ReportingState { get; set; }
        public Nullable<int> WA_ReportId { get; set; }
        public string VT_ReportId { get; set; }
    
        public virtual CSPAOrganization CSPAOrganization { get; set; }
        public virtual ProductBrick ProductBrick { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportAccountableOrganization> ReportAccountableOrganizations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportDetail> ReportDetails { get; set; }
    }
}
