//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportDetail
    {
        public int ReportDetailId { get; set; }
        public int ReportId { get; set; }
        public int ComponentId { get; set; }
        public int ChemicalId { get; set; }
        public int ChemicalFunctionId { get; set; }
        public Nullable<int> ConcentrationCategoryId { get; set; }
        public Nullable<int> ConcentrationValue { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual Chemical Chemical { get; set; }
        public virtual ChemicalFunction ChemicalFunction { get; set; }
        public virtual Component Component { get; set; }
        public virtual ConcentrationCategory ConcentrationCategory { get; set; }
        public virtual Report Report { get; set; }
    }
}
