//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        public int DocumentId { get; set; }
        public int ReportAccountableOrganizationId { get; set; }
        public string DocumentTitle { get; set; }
        public string PrimaryDocumentFlag { get; set; }
        public byte[] DocumentData { get; set; }
        public string DocumentExtension { get; set; }
        public int DocumentSize { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        public virtual ReportAccountableOrganization ReportAccountableOrganization { get; set; }
    }
}
