//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class hpcdsDbContext : DbContext
    {
        public hpcdsDbContext()
            : base("name=hpcdsDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Chemical> Chemicals { get; set; }
        public virtual DbSet<ChemicalFunction> ChemicalFunctions { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<ConcentrationCategory> ConcentrationCategories { get; set; }
        public virtual DbSet<CSPAOrganization> CSPAOrganizations { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<OrganizationRelationship> OrganizationRelationships { get; set; }
        public virtual DbSet<ProductBrick> ProductBricks { get; set; }
        public virtual DbSet<ProductClass> ProductClasses { get; set; }
        public virtual DbSet<ProductFamily> ProductFamilies { get; set; }
        public virtual DbSet<ProductSegment> ProductSegments { get; set; }
        public virtual DbSet<PublicViewableDateSetting> PublicViewableDateSettings { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<ReportAccountableOrganization> ReportAccountableOrganizations { get; set; }
        public virtual DbSet<ReportDetail> ReportDetails { get; set; }
        public virtual DbSet<UserAccount> UserAccounts { get; set; }
        public virtual DbSet<ProductCategory> ProductCategories { get; set; }
        public virtual DbSet<vQuestion> vQuestions { get; set; }
        public virtual DbSet<vUserRole> vUserRoles { get; set; }
        public virtual DbSet<vOrganization> vOrganizations { get; set; }
        public virtual DbSet<L_Country> L_Country { get; set; }
        public virtual DbSet<L_State> L_State { get; set; }
        public virtual DbSet<InventoryBNPM> InventoryBNPMs { get; set; }
        public virtual DbSet<InventoryBNPMChemical> InventoryBNPMChemicals { get; set; }
        public virtual DbSet<vInventoryByOrg> vInventoryByOrgs { get; set; }
        public virtual DbSet<vInventoryBnPmByChem> vInventoryBnPmByChems { get; set; }
        public virtual DbSet<vSearchReport> vSearchReports { get; set; }
        public virtual DbSet<vInventoryBnPmWithChem> vInventoryBnPmWithChems { get; set; }
    }
}
