//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductClass
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductClass()
        {
            this.ProductBricks = new HashSet<ProductBrick>();
        }
    
        public int ProductClassId { get; set; }
        public string ProductClassCode { get; set; }
        public string ProductClassDescription { get; set; }
        public int ProductFamilyId { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductBrick> ProductBricks { get; set; }
        public virtual ProductFamily ProductFamily { get; set; }
    }
}
