//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductCategory
    {
        public int ProductBrickId { get; set; }
        public string ProductBrickCode { get; set; }
        public string ProductBrickDescription { get; set; }
        public string ProductClassCode { get; set; }
        public string ProductClassDescription { get; set; }
        public string ProductFamilyCode { get; set; }
        public string ProductFamilyDescription { get; set; }
        public string ProductSegmentCode { get; set; }
        public string ProductSegmentDescription { get; set; }
    }
}
