//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public int UserAccountId { get; set; }
        public int AffiliationId { get; set; }
        public int OrganizationId { get; set; }
        public string DeletedAccountFlag { get; set; }
        public string BannedAccountFlag { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string BannedReasonDescription { get; set; }
    
        public virtual CSPAOrganization CSPAOrganization { get; set; }
    }
}
