//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vInventoryBnPmWithChem
    {
        public int InventoryBNPMId { get; set; }
        public int OrganizationId { get; set; }
        public string OrganizationName { get; set; }
        public string BrandName { get; set; }
        public string ProductModel { get; set; }
        public string ChemicalNames { get; set; }
        public Nullable<long> rownum { get; set; }
    }
}
