// <auto-generated />
namespace hpcds.Migrations.AuthDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Del_OrgAndAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Del_OrgAndAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201903250005494_Del_OrgAndAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
