// <auto-generated />
namespace hpcds.Migrations.AuthDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Mod_OrgId_2IntType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mod_OrgId_2IntType));
        
        string IMigrationMetadata.Id
        {
            get { return "201903080557227_Mod_OrgId_2IntType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
