//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chemical
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Chemical()
        {
            this.ReportDetails = new HashSet<ReportDetail>();
            this.InventoryBNPMChemicals = new HashSet<InventoryBNPMChemical>();
        }
    
        public int ChemicalId { get; set; }
        public string ChemicalName { get; set; }
        public string CASNumber { get; set; }
        public string EuropeanCommissionNumber { get; set; }
        public string EPAIdentifier { get; set; }
        public string IsSingleChemicalFlag { get; set; }
        public string IsVisibleFlag { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedByName { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<int> CASNumberSortValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportDetail> ReportDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryBNPMChemical> InventoryBNPMChemicals { get; set; }
    }
}
