//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryBNPM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InventoryBNPM()
        {
            this.InventoryBNPMChemicals = new HashSet<InventoryBNPMChemical>();
        }
    
        public int InventoryBNPMId { get; set; }
        public int OrganizationId { get; set; }
        public string BrandName { get; set; }
        public string ProductModel { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string VT_ManufacturerID { get; set; }
        public string VT_ManufacturerName { get; set; }
        public Nullable<int> cntOfBrands { get; set; }
        public Nullable<int> cntOfModels { get; set; }
        public Nullable<int> cntOfChemicals { get; set; }
        public string CreatedByName { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedByName { get; set; }
        public System.DateTime ModifiedOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryBNPMChemical> InventoryBNPMChemicals { get; set; }
    }
}
