//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_State
    {
        public int Id { get; set; }
        public string CountryCode { get; set; }
        public string AlphaCode { get; set; }
        public string StateName { get; set; }
        public string FIPSCode { get; set; }
        public string UPDATED_BY { get; set; }
        public System.DateTime UPDATED_ON { get; set; }
    
        public virtual L_Country L_Country { get; set; }
    }
}
