//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vOrganization
    {
        public int ID { get; set; }
        public string PIN { get; set; }
        public string OrganizationName { get; set; }
        public bool IsLegacy { get; set; }
        public string LegacyWaPins { get; set; }
        public bool IsActive { get; set; }
        public string ContactUserId { get; set; }
        public string DUNSNumber { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProv { get; set; }
        public string PostalCodeNumber { get; set; }
        public string CountryCd { get; set; }
        public int AddressType { get; set; }
    }
}
