//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HPCDS.OData.WebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSearchReport
    {
        public string OrganizationName { get; set; }
        public string ContactUserId { get; set; }
        public string DUNSNumber { get; set; }
        public string Email { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string JobTitle { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public string City { get; set; }
        public string StateProv { get; set; }
        public string PostalCodeNumber { get; set; }
        public string CountryCd { get; set; }
        public string ProductBrickDescription { get; set; }
        public string ProductClassDescription { get; set; }
        public string ProductFamilyDescription { get; set; }
        public string ProductSegmentDescription { get; set; }
        public string ComponentName { get; set; }
        public Nullable<bool> InaccessibleComponent { get; set; }
        public string ProductBrandName { get; set; }
        public string ProductModel { get; set; }
        public Nullable<int> UnitSoldInOR { get; set; }
        public Nullable<int> UnitOfferedForSale { get; set; }
        public string AttachedFiles { get; set; }
        public string ChemicalName { get; set; }
        public string CASNumber { get; set; }
        public string ConcentrationCategoryName { get; set; }
        public string ChemicalFunctionName { get; set; }
        public string States { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
        public int SelectedCompany { get; set; }
        public string TargetAgeGroupDescription { get; set; }
        public Nullable<int> ProductBricks { get; set; }
        public int SelectedComponent { get; set; }
        public int Chemicals { get; set; }
        public int SelectedFunction { get; set; }
    }
}
